# Generated by Django 5.0.1 on 2024-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_product_price_product_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='normal_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
