# Generated by Django 5.0.1 on 2024-06-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nomal_price',
            new_name='normal_price',
        ),
    ]
