# Generated by Django 5.0.6 on 2024-08-03 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_orderproduct_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.CreateModel(
            name='OrderPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('express', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('other', models.TextField(blank=True, null=True)),
                ('stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('slip', models.ImageField(blank=True, null=True, upload_to='slip')),
                ('slip_time', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(choices=[('KBank', 'KBank'), ('SCB', 'SCB'), ('TTB', 'TTB'), ('KTB', 'KTB'), ('BBL', 'BBL'), ('BAY', 'BAY'), ('อื่นๆ', 'อื่นๆ')], default='KBank', max_length=50)),
                ('paymentid', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
