# Generated by Django 5.0.6 on 2024-08-03 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_order_user_orderpending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPending',
            new_name='CartOrder',
        ),
    ]
