# Generated by Django 5.0.6 on 2024-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_orderpending_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='name',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
