# Generated by Django 5.0.6 on 2024-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_cartorder_name_cartorder_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
