# Generated by Django 5.0.6 on 2024-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_machine_comments_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='price_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
